/**:
  ros__parameters:
    # dynamic_change_pattern
    max_detectable_height: 1.4 # m
    min_detectable_height: 0.11 # m
    pixel_size: 0.0063 # px/m

    # Common
    max_transport_time: 1200.0 # s
    max_translational_velocity: 0.5 # 0.26 # m/s
    max_rotational_velocity: 1.82 # rad/s
    turn_timer_period: 3.46 #s

    # caging and pushing pattern
    goal_search_timer_period: 12.0 # s
    object_search_timer_period: 1.0 # s

    # search_object_pattern
    wall_follow_timer_period: 10.0 # s

    # caging_pattern
    robot_length: 0.20925 # m
    robot_radius: 0.220 # m
    object_name: 'Circle_1,25x1,2_d0,8' # Gazebomodelname  # Circle_1,25x1,2_d0,8 | concave_4x3,66x0,2_d0,8 | Rectangle_3x2x0,2_d0,8 | Triangle_3x0,2_d0,8
    goal_name: 'Goal' # Gazebomodelname

    # random_walk_pattern
    random_walk_timer_period: 0.25
    random_walk_linear: 0.26
    random_walk_angular: 1.82
    random_walk_rot_interval: 3.5
    random_walk_lin_interval_min: 10.0
    random_walk_lin_interval_max: 15.0

    # evaluation
    evaluation_path: '/src/evaluation/' # /home/lydia/





