/**:
  ros__parameters:
    # search_object_pattern
    wall_follow_timer_period: 10.0 # s
    max_transport_time: 1200.0 # s
    turn_timer_period: 3.46 # s
    goal_search_timer_period: 12.0 # s
    object_search_timer_period: 1.0 # s

    # Common
    max_translational_velocity: 0.5 # 0.26 # m/s
    max_rotational_velocity: 1.82 # rad/s

    # nur zur Auswertung
    object_name: 'Green_Quader_4x4x2' # Gazebomodelname  # Green | Green_Quader_3x2 | Green_Quader_4x4x2 | unit_cylinder_radius_1,5m | concave
    goal_name: 'Goal' # Gazebomodelname
